runtime: go
env: flex
api_version: go1.8
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
readiness_check:
  path: '/readiness_check'
  check_interval_sec: 60
  app_start_timeout_sec: 300
beta_settings:
  cloud_sql_instances: "genepse-186713:asia-northeast1:genepse"
env_variables:
  GENEPSE_MYSQL_CONNECTION: root:hogehoge@unix(/cloudsql/genepse-186713:asia-northeast1:genepse)/mobile_api?charset=utf8&parseTime=True&loc=Local
