runtime: go
env: flex
api_version: go1.8
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 20
readiness_check:
  path: '/readiness_check'
  app_start_timeout_sec: 300
beta_settings:
  cloud_sql_instances: "genepse-186713:asia-northeast1:genepse"
env_variables:
  GENEPSE_MYSQL_CONNECTION: root:tsuba2896@unix(/cloudsql/genepse-186713:asia-northeast1:genepse)/mobile_api
